table Dim_Vendor
	lineageTag: e005c6ee-6bd6-40d4-bacb-4e613596b7ea

	column No_
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(20)
		lineageTag: 682ad8de-b73c-447b-b34d-13deb00c5f46
		summarizeBy: none
		sourceColumn: No_

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 3f8c7fbe-6520-4c92-84a8-22ca90a52595
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Search Name'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: cdd5ff28-b85b-4f5e-925f-3f770df33818
		summarizeBy: none
		sourceColumn: Search Name

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 5c00a16d-43f6-4422-ba6a-1eddf7dd361f
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(30)
		lineageTag: 51deae9b-d9ed-46d0-b3b6-b021d5f962fe
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Contact
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: e4165c5e-53d9-4de0-a8ea-265e9bc224a9
		summarizeBy: none
		sourceColumn: Contact

		annotation SummarizationSetBy = Automatic

	column 'Currency Code'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(10)
		lineageTag: 1a4b2501-db72-4a37-85b8-f7dbc4a50af3
		summarizeBy: none
		sourceColumn: Currency Code

		annotation SummarizationSetBy = Automatic

	column 'Language Code'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(10)
		lineageTag: e5d2163f-51be-42cd-a8b4-6d903100dfb7
		summarizeBy: none
		sourceColumn: Language Code

		annotation SummarizationSetBy = Automatic

	column 'Invoice Disc_ Code'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(20)
		lineageTag: 39fa7e43-a8d4-4ea3-8149-00c9dd2563c3
		summarizeBy: none
		sourceColumn: Invoice Disc_ Code

		annotation SummarizationSetBy = Automatic

	column 'Country_Region Code'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(10)
		lineageTag: a8abe03a-89d4-47aa-b49a-33a306997deb
		summarizeBy: none
		sourceColumn: Country_Region Code

		annotation SummarizationSetBy = Automatic

	column 'Last Modified Date Time'
		dataType: dateTime
		isNullable: false
		formatString: General Date
		sourceProviderType: datetime
		lineageTag: 3e3a979c-5058-4862-ae84-80f14d872d3f
		summarizeBy: none
		sourceColumn: Last Modified Date Time

		variation Variation
			isDefault
			relationship: 61c04b65-e3c4-43fd-8341-948932953545
			defaultHierarchy: LocalDateTable_4315d579-b2d7-4238-aba0-3e3d45909bbe.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Last Date Modified'
		dataType: dateTime
		isNullable: false
		formatString: General Date
		sourceProviderType: datetime
		lineageTag: 202f9d26-f7d8-489a-b88f-fed70e559d5e
		summarizeBy: none
		sourceColumn: Last Date Modified

		variation Variation
			isDefault
			relationship: 0e498ec7-d49b-417b-ad10-a0323151f46c
			defaultHierarchy: LocalDateTable_a630ff3d-80e2-4f31-82b2-34a9acdddff2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Prices Including VAT'
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: 0aa5c2ef-87b0-402a-ad0a-a841bc84922f
		summarizeBy: sum
		sourceColumn: Prices Including VAT

		annotation SummarizationSetBy = Automatic

	column 'Primary Contact No_'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(20)
		lineageTag: 4f6dff3d-fa02-4cbd-8c73-b7d3e10fa1e0
		summarizeBy: none
		sourceColumn: Primary Contact No_

		annotation SummarizationSetBy = Automatic

	column 'Location Code'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(10)
		lineageTag: a172f4cb-099c-4340-ab11-14c6097aab67
		summarizeBy: none
		sourceColumn: Location Code

		annotation SummarizationSetBy = Automatic

	column 'Currency Id'
		dataType: string
		isNullable: false
		sourceProviderType: uniqueidentifier
		lineageTag: 77a85778-ca3a-439e-9821-453fed656886
		summarizeBy: none
		sourceColumn: Currency Id

		annotation SummarizationSetBy = Automatic

	partition Dim_Vendor = m
		mode: import
		source =
				let
				    Source = Sql.Database("arggotest1.database.windows.net", "DynamicsBC_CatalinT"),
				    #"dbo_CRONUS International Ltd_$Vendor$437dbf0e-84ff-417a-965d-ed2bb9650972" = Source{[Schema="dbo",Item="CRONUS International Ltd_$Vendor$437dbf0e-84ff-417a-965d-ed2bb9650972"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"dbo_CRONUS International Ltd_$Vendor$437dbf0e-84ff-417a-965d-ed2bb9650972",{"Name 2", "Address 2", "Phone No_", "Telex No_", "Our Account No_", "Global Dimension 1 Code", "Global Dimension 2 Code", "Budgeted Amount", "Vendor Posting Group", "Territory Code", "Registration Number", "Statistics Group", "Payment Terms Code", "Fin_ Charge Terms Code", "Purchaser Code", "Shipment Method Code", "Shipping Agent Code", "Blocked", "Pay-to Vendor No_", "Priority", "Payment Method Code", "Format Region", "Application Method", "Fax No_", "Telex Answer Back", "VAT Registration No_", "Gen_ Bus_ Posting Group", "GLN", "Post Code", "County", "EORI Number", "E-Mail", "Home Page", "No_ Series", "Tax Area Code", "Tax Liable", "VAT Bus_ Posting Group", "Block Payment Tolerance", "IC Partner Code", "Prepayment _", "Partner Type", "Intrastat Partner Type", "Exclude from Pmt_ Practices", "Company Size Code", "Image", "Privacy Blocked", "Disable Search by Name", "Creditor No_", "Allow Multiple Posting Groups", "Preferred Bank Account Code", "Coupled to CRM", "Cash Flow Payment Terms Code", "Mobile Phone No_", "Responsibility Center", "Lead Time Calculation", "Price Calculation Method", "Base Calendar Code", "Document Sending Profile", "Validate EU Vat Reg_ No_", "Payment Terms Id", "Payment Method Id", "Over-Receipt Code", "$systemId", "$systemCreatedAt", "$systemCreatedBy", "$systemModifiedAt", "$systemModifiedBy"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

